version: '3.5'

services: 
    frontend:
        container_name: ttfrontend
        build: ./frontend
        stdin_open: true
        tty: true
        volumes:
            - ./frontend:/frontend
        ports:
            - 3000:3000
    backend:
        container_name: ttbackend
        build: ./backend
        volumes:
            - ./backend:/backend
        ports:
            - 8000:8000
    nginx:
        container_name: ttproxy
        image: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        depends_on: 
            - frontend
            - backend